# Generated by Django 6.0.5 on 2026-06-02 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalization',
            name='admitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='clinical.bed'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='referring_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referring_hospitalizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalizations', to='clinical.patient'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clinical.department'),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='clinical.room'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('building', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('department', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('room', 'label')},
        ),
    ]
