# Generated by Django 6.0.5 on 2026-06-06 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_patient_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerHospital',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('specialties', models.CharField(blank=True, help_text='Spécialités disponibles, séparées par des virgules', max_length=500)),
                ('available_beds', models.PositiveSmallIntegerField(default=0)),
                ('total_beds', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_transfers', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'hôpital partenaire',
                'verbose_name_plural': 'hôpitaux partenaires',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InterHospitalTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('clinical_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Refusé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inter_hospital_transfers', to='clinical.hospitalization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfers_requested', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfers_validated', to=settings.AUTH_USER_MODEL)),
                ('partner_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='clinical.partnerhospital')),
            ],
            options={
                'verbose_name': 'transfert inter-établissement',
                'ordering': ['-created_at'],
            },
        ),
    ]
