# Generated by Django 6.0.5 on 2026-06-06 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_partner_hospital_inter_transfer'),
        ('documents', '0002_patient_movement_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'En cours'), ('DISCHARGED', 'Sortie'), ('TRANSFERRED', 'Transféré'), ('CANCELLED', 'Annulée')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='PatientMovementHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ADMISSION', 'Admission'), ('ADMISSION_CORRECTION', "Correction date d'admission"), ('ADMISSION_CANCEL', "Annulation d'admission"), ('DISCHARGE', 'Sortie'), ('INTERNAL_TRANSFER', 'Transfert interne'), ('INTER_TRANSFER', 'Transfert inter-établissement')], max_length=30)),
                ('event_at', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_events', to='documents.document')),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movement_history', to='clinical.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_history', to='clinical.patient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique mouvement patient',
                'verbose_name_plural': 'historiques mouvements patients',
                'ordering': ['-event_at', '-created_at'],
            },
        ),
    ]
