# Blueprint Render — SGHL (PostgreSQL obligatoire)

services:
  - type: web
    name: sghl-web
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/sante/
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DB_SSLMODE
        value: "require"
      - key: RENDER_DB_REGION
        value: "oregon"
      - key: SECRET_KEY
        generateValue: true
      - key: FIELD_ENCRYPTION_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: WEB_CONCURRENCY
        value: "1"
      - key: SEED_ON_BOOT
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: sghl-db
          property: connectionString
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

databases:
  - name: sghl-db
    plan: free
    region: oregon
    databaseName: sghl
    user: sghl
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
