# Generated by Django 6.0.5 on 2026-06-13 16:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_mobile_money_methods'),
        ('clinical', '0006_patient_movement_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='declared_by_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvoicePatientDeclaration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('MTN', 'MTN Mobile Money')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PAID', 'Payée'), ('UNPAID', 'Impayée')], max_length=10)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('declared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_declarations', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_declarations', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_declarations', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'déclaration paiement patient',
                'ordering': ['-created_at'],
            },
        ),
    ]
