# Generated by Django 6.0.5 on 2026-06-02 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_icd10code_careplan_caretask_consultation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(default='blood', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('turnaround_hours', models.PositiveSmallIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "type d'examen",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ORDERED', 'Commandé'), ('COLLECTED', 'Prélevé'), ('ASSIGNED', 'Affecté'), ('RESULTS_ENTERED', 'Résultats saisis'), ('VALIDATED', 'Validé'), ('PUBLISHED', 'Publié')], default='ORDERED', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinical.hospitalization')),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_ordered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='clinical.patient')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_validated', to=settings.AUTH_USER_MODEL)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='laboratory.labtesttype')),
            ],
            options={
                'verbose_name': 'commande labo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_data', models.JSONField(default=dict)),
                ('interpretation', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_entered', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.laborder')),
            ],
            options={
                'verbose_name': 'résultat labo',
            },
        ),
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to=settings.AUTH_USER_MODEL)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='laboratory.laborder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
