# Generated by Django 6.0.5 on 2026-06-02 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0003_icd10code_careplan_caretask_consultation_and_more'),
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('PRESCRIPTION', 'Ordonnance'), ('LAB_REPORT', 'Compte-rendu labo'), ('INVOICE', 'Facture'), ('IMAGING', 'Imagerie'), ('OTHER', 'Autre')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('hospitalization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clinical.hospitalization')),
                ('lab_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='laboratory.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='clinical.patient')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(default='VIEW', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accès document',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
