# Generated by Django 6.0.5 on 2026-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('PRESCRIPTION', 'Ordonnance'), ('LAB_REPORT', 'Compte-rendu labo'), ('INVOICE', 'Facture'), ('IMAGING', 'Imagerie'), ('ADMISSION', "Attestation d'admission"), ('DISCHARGE', 'Attestation de sortie'), ('TRANSFER', 'Attestation de transfert'), ('OTHER', 'Autre')], max_length=20),
        ),
    ]
