# Generated by Django 6.0.5 on 2026-06-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETARY', 'Secrétaire'), ('ACCOUNTANT', 'Comptable'), ('DOCTOR', 'Médecin'), ('NURSE', 'Infirmier(ère)'), ('BIOLOGIST', 'Biologiste'), ('PHARMACIST', 'Pharmacien'), ('PATIENT', 'Patient')], max_length=32, unique=True),
        ),
    ]
