# Generated by Django 6.0.5 on 2026-06-02 16:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(default='comprimé', max_length=50)),
                ('unit', models.CharField(default='unité', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reorder_threshold', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'médicament',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacy.medicine')),
            ],
            options={
                'verbose_name': 'lot stock',
                'ordering': ['expiry_date'],
                'unique_together': {('medicine', 'lot_number')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pharmacy.stocklot')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mouvement stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
